kind: pipeline
name: release

steps:
  - name: test
    image: golang
    commands:
      - go test ./...

  - name: build
    image: golang
    commands:
      -              go build -mod=vendor -ldflags="-s -w" -o drone-helm3-linux-amd64 .
      - GOARCH=386   go build -mod=vendor -ldflags="-s -w" -o drone-helm3-linux-386 .
      - GOARCH=arm   go build -mod=vendor -ldflags="-s -w" -o drone-helm3-linux-arm .
      - GOARCH=arm64 go build -mod=vendor -ldflags="-s -w" -o drone-helm3-linux-arm64 .
    when:
      event: tag
    depends_on:
      - test

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - drone-helm3-linux-386
        - drone-helm3-linux-amd64
        - drone-helm3-linux-arm
        - drone-helm3-linux-arm64
      checksum:
        - md5
        - sha1
        - sha256
    when:
      event: tag
    depends_on:
      - build

---
kind: pipeline
name: linux-amd64-docker

platform:
  os: linux
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true

depends_on:
  - release

---
kind: pipeline
name: linux-arm64-docker

platform:
  os: linux
  arch: arm64

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: linux-arm64
      build_args:
        - ARCH=arm64

depends_on:
  - release